name: Update Current Template IDs

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update-ids:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps and run update script
        run: |
          npm install node-fetch
          node dashboard/backend-scripts/update-templates.js

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add dashboard/templates.json if changed
        run: |
          git add dashboard/templates.json
          # Check if the file has changes staged
          if ! git diff --cached --quiet; then
            git commit -m "Update current_id from Wikipedia API"
            git push
          else
            echo "No changes to commit"
          fi